#!/bin/bash

IMAGE_TAG="x86_64"

case "$1" in
  --arm64)
    IMAGE_TAG="arm64"
    shift
    ;;

  --arm32)
    IMAGE_TAG="arm32"
    shift
    ;;

  --help)
    echo "usage: $0 [--arm64|armhf] ..."
    exit 1
    ;;
esac

exec docker run \
  --rm \
  -it \
  -e HOME -v "${HOME}:${HOME}" \
  -e USER \
  -u "$(id -u):$(id -g)" \
  $(id -Gz | xargs -0 -n1 -I{} echo "--group-add={}") \
  -v /etc/passwd:/etc/passwd:ro \
  -v /dev/bus/usb:/dev/bus/usb \
  -v "${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}" \
  -e SSH_AUTH_SOCK \
  --privileged \
  -h rock64-build-env \
  -v "${PWD}:${PWD}" \
  -w "${PWD}" \
  "ayufan/rock64-dockerfiles:$IMAGE_TAG" \
  "$@"
